fix(deps): update module github.com/traefik/traefik/v2 to v3
dfds/infrastructure-modules pull request #1493
Opened 2024-07-31 06:35 UTC by devex-sa

This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [github.com/traefik/traefik/v2](https://togithub.com/traefik/traefik) | require | major | `v2.11.6` -> `v3.1.1` |

---

### Release Notes

<details>
<summary>traefik/traefik (github.com/traefik/traefik/v2)</summary>

### [`v3.1.1`](https://togithub.com/traefik/traefik/blob/HEAD/CHANGELOG.md#v311-2024-07-30)

[Compare Source](https://togithub.com/traefik/traefik/compare/v3.1.0...v3.1.1)

[All Commits](https://togithub.com/traefik/traefik/compare/v3.1.0...v3.1.1)

**Bug fixes:**

-   **\[grpc]** Bump google.golang.org/grpc to v1.64.1 ([#&#8203;10938](https://togithub.com/traefik/traefik/pull/10938) by [kevinpollet](https://togithub.com/kevinpollet))
-   **\[k8s/gatewayapi]** Do not update route status when nothing changed ([#&#8203;10940](https://togithub.com/traefik/traefik/pull/10940) by [kevinpollet](https://togithub.com/kevinpollet))
-   **\[metrics]** Fix grafana dashboard to work with scrape interval greater than 15s ([#&#8203;10936](https://togithub.com/traefik/traefik/pull/10936) by [davhdavh](https://togithub.com/davhdavh))
-   **\[metrics]** Update open connections gauge with connections count ([#&#8203;10905](https://togithub.com/traefik/traefik/pull/10905) by [rtribotte](https://togithub.com/rtribotte))
-   **\[metrics]** Use ServiceName in traefik_service_server_up metric ([#&#8203;10838](https://togithub.com/traefik/traefik/pull/10838) by [KrishnaSindhur](https://togithub.com/KrishnaSindhur))

**Documentation:**

-   **\[k8s]** Remove duplicated kubectl apply in Kubernetes Gateway documentation ([#&#8203;10931](https://togithub.com/traefik/traefik/pull/10931) by [battery-staple](https://togithub.com/battery-staple))

**Misc:**

-   Merge v2.11 into v3.1 ([#&#8203;10925](https://togithub.com/traefik/traefik/pull/10925) by [mmatur](https://togithub.com/mmatur))

### [`v3.1.0`](https://togithub.com/traefik/traefik/blob/HEAD/CHANGELOG.md#v310-2024-07-15)

[Compare Source](https://togithub.com/traefik/traefik/compare/v3.0.4...v3.1.0)

[All Commits](https://togithub.com/traefik/traefik/compare/v3.1.0-rc1...v3.1.0)

**Enhancements:**

-   **\[k8s,k8s/gatewayapi]** Support invalid HTTPRoute status ([#&#8203;10714](https://togithub.com/traefik/traefik/pull/10714) by [kevinpollet](https://togithub.com/kevinpollet))
-   **\[k8s,k8s/gatewayapi]** KubernetesGateway provider is no longer experimental ([#&#8203;10840](https://togithub.com/traefik/traefik/pull/10840) by [rtribotte](https://togithub.com/rtribotte))
-   **\[k8s,k8s/gatewayapi]** Bump Gateway API to v1.1.0 ([#&#8203;10835](https://togithub.com/traefik/traefik/pull/10835) by [kevinpollet](https://togithub.com/kevinpollet))
-   **\[k8s,k8s/gatewayapi]** Fix route attachments to gateways ([#&#8203;10761](https://togithub.com/traefik/traefik/pull/10761) by [kevinpollet](https://togithub.com/kevinpollet))
-   **\[k8s,k8s/gatewayapi]** Support HTTPRoute method and query param matching ([#&#8203;10815](https://togithub.com/traefik/traefik/pull/10815) by [kevinpollet](https://togithub.com/kevinpollet))
-   **\[k8s,k8s/gatewayapi]** Support HTTPURLRewrite filter ([#&#8203;10571](https://togithub.com/traefik/traefik/pull/10571) by [SantoDE](https://togithub.com/SantoDE))
-   **\[k8s,k8s/gatewayapi]** Set Gateway HTTPRoute status ([#&#8203;10667](https://togithub.com/traefik/traefik/pull/10667) by [kevinpollet](https://togithub.com/kevinpollet))
-   **\[k8s,k8s/gatewayapi]** Support ReferenceGrant for HTTPRoute backends ([#&#8203;10771](https://togithub.com/traefik/traefik/pull/10771) by [rtribotte](https://togithub.com/rtribotte))
-   **\[k8s,k8s/gatewayapi]** Compute HTTPRoute priorities ([#&#8203;10766](https://togithub.com/traefik/traefik/pull/10766) by [kevinpollet](https://togithub.com/kevinpollet))
-   **\[k8s,k8s/gatewayapi]** Support RegularExpression for path matching ([#&#8203;10717](https://togithub.com/traefik/traefik/pull/10717) by [dmavrommatis](https://togithub.com/dmavrommatis))
-   **\[k8s/crd,k8s]** Support HealthCheck for ExternalName services ([#&#8203;10467](https://togithub.com/traefik/traefik/pull/10467) by [marcmognol](https://togithub.com/marcmognol))
-   **\[k8s/ingress,k8s/crd,k8s,k8s/gatewayapi]** Migrate to EndpointSlices API  ([#&#8203;10664](https://togithub.com/traefik/traefik/pull/10664) by [jnoordsij](https://togithub.com/jnoordsij))
-   **\[k8s/ingress,k8s/crd,k8s]** Change log level from Warning to Info when ExternalName services is enabled ([#&#8203;10682](https://togithub.com/traefik/traefik/pull/10682) by [marcmognol](https://togithub.com/marcmognol))
-   **\[k8s/ingress,k8s/crd,k8s]** Allow to use internal Node IPs for NodePort services ([#&#8203;10278](https://togithub.com/traefik/traefik/pull/10278) by [jorisvergeer](https://togithub.com/jorisvergeer))
-   **\[middleware,k8s,k8s/gatewayapi]** Improve HTTPRoute Redirect Filter with port and scheme ([#&#8203;10784](https://togithub.com/traefik/traefik/pull/10784) by [rtribotte](https://togithub.com/rtribotte))
-   **\[middleware,k8s,k8s/gatewayapi]** Support HTTPRoute redirect port and scheme ([#&#8203;10802](https://togithub.com/traefik/traefik/pull/10802) by [rtribotte](https://togithub.com/rtribotte))
-   **\[middleware]** Support Content-Security-Policy-Report-Only in the headers middleware ([#&#8203;10709](https://togithub.com/traefik/traefik/pull/10709) by [SpecLad](https://togithub.com/SpecLad))
-   **\[middleware]** Add support for Zstandard to the compression middleware ([#&#8203;10660](https://togithub.com/traefik/traefik/pull/10660) by [Belphemur](https://togithub.com/Belphemur))
-   **\[plugins]** Enhance wasm plugins ([#&#8203;10829](https://togithub.com/traefik/traefik/pull/10829) by [juliens](https://togithub.com/juliens))
-   **\[plugins]** Add logs for plugins load ([#&#8203;10848](https://togithub.com/traefik/traefik/pull/10848) by [mmatur](https://togithub.com/mmatur))
-   **\[server]** Support systemd socket-activation ([#&#8203;10399](https://togithub.com/traefik/traefik/pull/10399) by [juliens](https://togithub.com/juliens))

**Bug fixes:**

-   **\[k8s,k8s/gatewayapi]** Retry on Gateway API resource status update ([#&#8203;10881](https://togithub.com/traefik/traefik/pull/10881) by [rtribotte](https://togithub.com/rtribotte))
-   **\[k8s,k8s/gatewayapi]** Do not disable Gateway API provider if not enabled in experimental ([#&#8203;10862](https://togithub.com/traefik/traefik/pull/10862) by [kevinpollet](https://togithub.com/kevinpollet))
-   **\[otel]** Bump opentelemetry-go to v1.28 ([#&#8203;10876](https://togithub.com/traefik/traefik/pull/10876) by [arukiidou](https://togithub.com/arukiidou))
-   **\[plugins]** Fix build only linux and darwin support wazergo ([#&#8203;10857](https://togithub.com/traefik/traefik/pull/10857) by [juliens](https://togithub.com/juliens))
-   **\[healthcheck,k8s/crd,k8s]** Fix Healthcheck default value for ExternalName services ([#&#8203;10778](https://togithub.com/traefik/traefik/pull/10778) by [kevinpollet](https://togithub.com/kevinpollet))
-   **\[middleware,metrics,tracing]** Upgrade to OpenTelemetry Semantic Conventions v1.26.0 ([#&#8203;10850](https://togithub.com/traefik/traefik/pull/10850) by [mmatur](https://togithub.com/mmatur))

**Documentation:**

-   **\[k8s,k8s/gatewayapi]** Fix the Kubernetes Gateway API documentation ([#&#8203;10844](https://togithub.com/traefik/traefik/pull/10844) by [nmengin](https://togithub.com/nmengin))
-   **\[k8s,k8s/gatewayapi]** Rework Kubernetes Gateway API documentation ([#&#8203;10897](https://togithub.com/traefik/traefik/pull/10897) by [kevinpollet](https://togithub.com/kevinpollet))
-   Prepare release v3.1.0-rc3 ([#&#8203;10872](https://togithub.com/traefik/traefik/pull/10872) by [rtribotte](https://togithub.com/rtribotte))
-   Prepare release v3.1.0-rc2 ([#&#8203;10860](https://togithub.com/traefik/traefik/pull/10860) by [kevinpollet](https://togithub.com/kevinpollet))
-   Prepare release v3.1.0-rc1 ([#&#8203;108 [...]

2024-07-31 06:35 UTC, devex-sa commented
### ⚠️ Artifact update problem

Renovate failed to update an artifact related to this branch. You probably do not want to merge this PR as-is.

♻ Renovate will retry this branch, including artifacts, only when one of the following happens:

 - any of the package files in this branch needs updating, or 
 - the branch becomes conflicted, or
 - you click the rebase/retry checkbox if found above, or
 - you rename this PR's title to start with "rebase!" to trigger it manually

The artifact failure details are included below:

##### File name: test/integration/suite/go.sum

```
Command failed: go get -d -t ./...
go: errors parsing go.mod:
/tmp/renovate/repos/github/dfds/infrastructure-modules/test/integration/suite/go.mod:3: invalid go version '1.22.0': must match format 1.23
/tmp/renovate/repos/github/dfds/infrastructure-modules/test/integration/suite/go.mod:5: unknown directive: toolchain

```

2024-07-31 07:40 UTC, rifisdfds requested changes
We are not yet using Traefik v3

2024-08-05 13:53 UTC, avnes commented
We need to postpone this for a while

2024-08-05 13:53 UTC, closed without merging

2024-08-05 14:34 UTC, devex-sa commented
### Renovate Ignore Notification

Because you closed this PR without merging, Renovate will ignore this update. You will not get PRs for *any* future `3.x` releases. But if you manually upgrade to `3.x` then Renovate will re-enable `minor` and `patch` updates automatically.

If you accidentally closed this PR, or if you changed your mind: rename this PR to get a fresh replacement PR.