Add support for EKS 1.20
dfds/infrastructure-modules pull request #232
Opened 2021-06-16 10:03 UTC by avnes

With a tactical fix for clusterrole when upgrading to coredns 1.8.3

2021-06-16 13:28 UTC, wcarlsen requested changes
Please only use null resources when official support is available https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/cluster_role

2021-06-16 13:28 UTC, wcarlsen commented on _sub/compute/eks-addons/main.tf
> +resource "null_resource" "coredns_clusterrole" {
This should not be a null resource but regular kubernetes provider resource, which should be possible with clusterroles or a kubectl resource.

2021-06-16 13:32 UTC, wcarlsen approved these changes
I still don't like the null resourdce clusterrole, but I guess we cannot manage this since CoreDNS is "AWS managing" it. LOL!

2021-06-17 14:19 UTC, abstrask commented
#235 seems to negate the need the TF changes. If you agree, maybe we can roll off everything except adding 1.20 to QA? @avnes

2021-06-17 14:20 UTC, abstrask requested changes
#235 seems to negate the need the TF changes. If you agree, maybe we can roll off everything except adding 1.20 to QA?

2021-06-17 14:29 UTC, avnes commented
> #235 seems to negate the need the TF changes. If you agree, maybe we can roll off everything except adding 1.20 to QA?

I am currently testing #235, and assuming it is successfull I will cancel this PR, and rather add a new PR for QA only. That way we won't pollute git history with reverts.

2021-06-18 07:11 UTC, avnes commented
I'll close this PR and open a new one for QA pipeline for EKS 1.20

2021-06-18 07:11 UTC, closed without merging