Handle EKS add-ons with native Terraform instead of kubectl
dfds/infrastructure-modules pull request #235
Opened 2021-06-16 21:20 UTC by abstrask

Replace null resources using `kubectl` with native [`aws_eks_addon`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon) resources.

Has the added benefit that the CNI will now be pulled from the ECR registry in the same region as cluster, instead of "us-west-2".

Minimum supported Kubernetes cluster version as of this change is 1.18.

2021-06-17 08:04 UTC, abstrask commented
@avnes Can you test if this change updates the CoreDNS cluster role, when upgrading to the latest CoreDNS version? Or help me test it out?

2021-06-17 11:20 UTC, abstrask commented
Test plan:

- New 1.19 cluster using same modules as current EKS pipeline (?ref=0.2.117)
- Output 'system:coredns' cluster role (look for 'endpointslices')
- Apply current branch on cluster phase (native TF addon management)
- Output 'system:coredns' cluster role (look for 'endpointslices')
- Upgrade cluster to 1.20 also using current branch
- Output 'system:coredns' cluster role (look for 'endpointslices')

2021-06-17 13:20 UTC, abstrask commented
Cluster role gets amended accordingly when upgrading to cluster 1.20, so I guess this can replace PR #232, @avnes ?

2021-06-17 15:05 UTC, avnes requested changes
I can confirm this works really well, and gets the job done when upgrading from EKS 1.19 and EKS 1.20 - I just have one doubt about the CNI version used. Please see other comment.

2021-06-17 15:05 UTC, avnes commented on _sub/compute/eks-addons/dependencies.tf
> +    "1.20" = "v1.7.5-eksbuild.2"
https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html#updating-vpc-cni-add-on recommends using CNI version 1.7.10

2021-06-17 15:05 UTC, avnes commented on _sub/compute/eks-addons/dependencies.tf
> +    "1.20" = "v1.7.5-eksbuild.2"
It is also CNI version 1.7.10 tested with in the null_provider update

2021-06-18 06:37 UTC, abstrask commented
I get this using AWS CLI:

```
$ aws eks describe-addon-versions --kubernetes-version 1.18 --addon-name vpc-cni | jq -r '.addons[].addonVersions[] | select(.compatibilities[].defaultVersion == true) | .addonVersion'
v1.7.5-eksbuild.2

$ aws eks describe-addon-versions --kubernetes-version 1.19 --addon-name vpc-cni | jq -r '.addons[].addonVersions[] | select(.compatibilities[].defaultVersion == true) | .addonVersion'
v1.7.5-eksbuild.2

$ aws eks describe-addon-versions --kubernetes-version 1.20 --addon-name vpc-cni | jq -r '.addons[].addonVersions[] | select(.compatibilities[].defaultVersion == true) | .addonVersion'
v1.7.5-eksbuild.2
```

2021-06-18 06:44 UTC, avnes approved these changes

2021-06-18 06:59 UTC, merged