Version bump to kube-prometheus-stack in QA.
dfds/infrastructure-modules pull request #319
Opened 2021-09-23 14:12 UTC by dfds-pwes

Just a version bump on kube-prometheus-stack to have it test in QA.

2021-09-23 14:15 UTC, wcarlsen requested changes
How will you handle the migration required:
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-16x-to-17x
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-17x-to-18x

2021-09-23 14:26 UTC, dfds-pwes commented
Hey Willi.

Yes, I know that.  That is exactly what I did in my sandbox -all worked fine.

2021-09-24 08:29 UTC, avnes approved these changes
For new installs in QA this should be fine.

2021-09-24 08:33 UTC, wcarlsen approved these changes

2021-09-24 08:33 UTC, merged