CSI Driver v2
dfds/infrastructure-modules pull request #377
Opened 2022-01-04 12:52 UTC by dfds-pwes

Contains all changes required to allow us to move from the early releases of the CSI Driver to version 2.x.x and beyond.

2022-01-04 13:07 UTC, avnes commented
I suppose .ionide/symbolCache.db is not supposed to be commited to Git :)

2022-01-04 13:10 UTC, avnes requested changes
Remove binary file symbolCache.db

2022-01-04 16:09 UTC, avnes approved these changes

2022-01-05 11:50 UTC, dfds-pwes commented on _sub/compute/helm-ebs-csi-driver/main.tf
>  EOF
Ignore added in the code as this is a vendor provider policy.

2022-01-05 11:50 UTC, dfds-pwes commented on _sub/compute/helm-ebs-csi-driver/main.tf
>  EOF
Ignore added in the code as this is a vendor provider policy.

2022-01-05 11:54 UTC, avnes approved these changes

2022-01-05 12:38 UTC, samidbb approved these changes

2022-01-06 10:14 UTC, rifisdfds approved these changes

2022-01-11 09:10 UTC, merged