Update Terraform kubernetes to ~> 2.13.0
dfds/infrastructure-modules pull request #525
Opened 2022-08-24 05:25 UTC by devex-sa

This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [kubernetes](https://registry.terraform.io/providers/hashicorp/kubernetes) ([source](https://togithub.com/hashicorp/terraform-provider-kubernetes)) | required_provider | minor | `~> 2.12.0` -> `~> 2.13.0` |

---

### Release Notes

<details>
<summary>hashicorp/terraform-provider-kubernetes</summary>

### [`v2.13.0`](https://togithub.com/hashicorp/terraform-provider-kubernetes/blob/HEAD/CHANGELOG.md#&#8203;2130-August-23-2022)

[Compare Source](https://togithub.com/hashicorp/terraform-provider-kubernetes/compare/v2.12.1...v2.13.0)

BUG FIXES:

-   Starting from Kubernetes 1.24.0 service account token is not automatically generated, thus it has to create separately. The following resources were updated to handle this change: `d/kubernetes_service_account`, `r/kubernetes_default_service_account`, `r/kubernetes_service_account`. For Kubernetes clusters running v1.24+ `default_secret_name` will be empty. A warning message will be printed once any of the above resources are in use. ([#&#8203;1792](https://togithub.com/hashicorp/terraform-provider-kubernetes/issues/1792))

IMPROVEMENTS:

-   `r/kubernetes_manifest`: Better error messages from OpenAPI schema transformations ([#&#8203;1780](https://togithub.com/hashicorp/terraform-provider-kubernetes/issues/1780))
-   Update documentation and correct some errors ([#&#8203;1768](https://togithub.com/hashicorp/terraform-provider-kubernetes/issues/1768), [#&#8203;1786](https://togithub.com/hashicorp/terraform-provider-kubernetes/issues/1786))
-   Update acceptance tests infrastructure code for GKE and AKE and related GitHub Actions

</details>

---

### Configuration

📅 **Schedule**: At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, click this checkbox.

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

2022-08-26 08:23 UTC, Ranixa requested changes
Code Freeze.

2022-11-14 11:34 UTC, rifisdfds approved these changes

2022-11-14 11:37 UTC, rifisdfds commented
Tested in sandbox. New `wait_for_service_account_token` attribute applied to resources does not appear to change behaviour

2022-11-14 12:07 UTC, Ranixa reviewed
OK, Fish has tested as required and updated to version required.

2022-11-14 12:07 UTC, Ranixa approved these changes

2022-11-14 12:10 UTC, merged