Updated eks addon versions
dfds/infrastructure-modules pull request #735
Opened 2023-03-08 14:35 UTC by Mik-Nord

2023-03-08 14:38 UTC, avnes requested changes

2023-03-08 14:38 UTC, avnes commented on _sub/compute/eks-addons/dependencies.tf
> +    "1.24" = "v1.12.5-eksbuild.1"
Please add 1.25 and its addons too

2023-03-08 14:48 UTC, avnes requested changes

2023-03-08 14:48 UTC, avnes commented on _sub/compute/eks-addons/dependencies.tf
> +    "1.24" = "v1.9.3-eksbuild.2"
This should be v1.8.7-eksbuild.4, because this is the recommended version of coredns managed add-on for 1.24

2023-03-08 14:48 UTC, avnes commented on _sub/compute/eks-addons/dependencies.tf
> +    "1.24" = "v1.12.5-eksbuild.1"
v1.12.2-eksbuild.1 is the recommended version for 1.24 and 1.24 when using mnaged add-ons. Reference: https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html

2023-03-08 14:48 UTC, avnes commented on _sub/compute/eks-addons/dependencies.tf
> +    "1.24" = "v1.24.9-eksbuild.1"
v1.24.7-eksbuild.2 is the recommended version for kube-proxy when using managed add-ons. Reference: https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html

2023-03-08 15:08 UTC, avnes requested changes

2023-03-08 15:08 UTC, avnes commented on _sub/compute/eks-addons/dependencies.tf
> +    "1.25" = "v1.12.5-eksbuild.1"
For 1.25 it should also be v1.12.2-eksbuild.1

2023-03-08 15:13 UTC, avnes requested changes

2023-03-08 15:13 UTC, avnes commented on _sub/compute/eks-addons/dependencies.tf
> +    "1.25" = "v1.12.5-eksbuild.1"
For 1.25 it should also be v1.12.2-eksbuild.1

2023-03-08 15:14 UTC, avnes approved these changes

2023-03-09 08:19 UTC, emil2k commented
@Mik-Nord Have you reviewed the changelogs for each addon?

2023-03-09 09:52 UTC, emil2k commented
@Mik-Nord You found the change logs for the vpc cni and ebs csi addons, here is the coredns chanelog:
https://github.com/coredns/coredns/releases
and the kube-proxy changelog seems to be embedded in the kubernetes changelog itself.

2023-03-09 11:03 UTC, emil2k approved these changes
Looks good, I merged master into this to get it to run on QA - if it passes merge it in.

2023-03-09 11:37 UTC, merged